### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'scrollWidth')

### ISSUE THREAD

**Issue by cameronjweeks** [BearToCode/carta#53] opened 2024-04-25 01:01 UTC
Error on load

carta-md.js?v=7095f9a7:2455 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollWidth')
    at overflowing (carta-md.js?v=7095f9a7:2455:41)
    at carta-md.js?v=7095f9a7:2456:14
    at carta-md.js?v=7095f9a7:186:32

**Comment by BearToCode** [comment] 2024-04-25 15:51
Hello, can you provide more information as well as a minimal reproducible example? It looks like a resize event is fired before the component is mounted, which should not happen.

**Comment by WillWilli** [comment] 2024-06-05 23:17
Hi @BearToCode 
I am also getting this error, please see this stack blitz which reproduces the error: https://stackblitz.com/edit/vitejs-vite-bgsby6?file=src%2FApp.svelte

**Comment by BearToCode** [comment] 2024-06-06 07:12
Should be fixed now. The example is now working in `v4.1.1`

**Closed by BearToCode** 2024-06-06 07:12 UTC
Labels: bug
